package:
  name: shakelib
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: https://github.com/usgs/shakelib.git

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: {{ GIT_BUILD_STR }}

requirements:
  build:
    - python
    - setuptools
  run:
    - python
